name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set-up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Get dependencies
      run: go mod tidy
    
    - name: Build binary
      run: CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: 2cheetah/telegram_news:latest

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client sshpass
  
    - name: Deploy to Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull 2cheetah/telegram_news:latest
          docker stop telegram_news || true
          docker rm telegram_news || true
          docker run -d --name telegram_news -e API_TOKEN="${{ secrets.API_TOKEN }}"" 2cheetah/telegram_news:latest
        EOF
